# This is a generated file. Not intended for manual editing.
services:
  leaderboardservice-api-1:
    build:
      context: "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService"
      dockerfile: "LeaderboardService.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "leaderboardservice.api:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "/Users/deniskornienko/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService/LeaderboardService.API:/app:rw"
    - "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService:/src:rw"
    - "/Users/deniskornienko/.local/share/JetBrains/RiderRemoteDebugger/2023.3.3/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/deniskornienko/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_5_01_21_36_59:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  leaderboardservice-api-2:
    build:
      context: "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService"
      dockerfile: "LeaderboardService.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "leaderboardservice.api:dev"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "/Users/deniskornienko/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService/LeaderboardService.API:/app:rw"
    - "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService:/src:rw"
    - "/Users/deniskornienko/.local/share/JetBrains/RiderRemoteDebugger/2023.3.3/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/deniskornienko/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_5_01_21_36_59:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  leaderboardservice-event-listener-1:
    build:
      context: "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService"
      dockerfile: "LeaderboardService.EventHost/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "leaderboardservice.eventhost:dev"
    ports:
    - "127.0.0.1:57005:57100"
    - "127.0.0.1:57205:57300"
    volumes:
    - "/Users/deniskornienko/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService/LeaderboardService.EventHost:/app:rw"
    - "/Users/deniskornienko/Desktop/Dotnet Projects/LeaderboardService/LeaderboardService:/src:rw"
    - "/Users/deniskornienko/.local/share/JetBrains/RiderRemoteDebugger/2023.3.3/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/deniskornienko/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_5_01_21_36_59:/var/opt/rider-debugger:rw"
    working_dir: "/app"
