# This is a generated file. Not intended for manual editing.
services:
  leaderboardservice-api-1:
    build:
      context: "D:\\Projects\\Dotnet\\leaderboard_service"
      dockerfile: "LeaderboardService.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/LeaderboardService.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "leaderboardservice.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Denys\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projects\\Dotnet\\leaderboard_service\\LeaderboardService.API:/app:rw"
    - "D:\\Projects\\Dotnet\\leaderboard_service:/src:rw"
    working_dir: "/app"
  leaderboardservice-api-2:
    build:
      context: "D:\\Projects\\Dotnet\\leaderboard_service"
      dockerfile: "LeaderboardService.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/LeaderboardService.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "leaderboardservice.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Denys\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projects\\Dotnet\\leaderboard_service\\LeaderboardService.API:/app:rw"
    - "D:\\Projects\\Dotnet\\leaderboard_service:/src:rw"
    working_dir: "/app"
  leaderboardservice-event-listener-1:
    build:
      context: "D:\\Projects\\Dotnet\\leaderboard_service"
      dockerfile: "LeaderboardService.EventHost/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/LeaderboardService.EventHost.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "leaderboardservice.eventhost:dev"
    ports: []
    volumes:
    - "C:\\Users\\Denys\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projects\\Dotnet\\leaderboard_service\\LeaderboardService.EventHost:/app:rw"
    - "D:\\Projects\\Dotnet\\leaderboard_service:/src:rw"
    working_dir: "/app"
  mock-server:
    build:
      context: "D:\\Projects\\Dotnet\\leaderboard_service"
      dockerfile: "LeaderboardService.Tests.MockGameServer/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/LeaderboardService.Tests.MockGameServer.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "leaderboardservice.tests.mockgameserver:dev"
    ports: []
    volumes:
    - "C:\\Users\\Denys\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projects\\Dotnet\\leaderboard_service\\LeaderboardService.Tests.MockGameServer:/app:rw"
    - "D:\\Projects\\Dotnet\\leaderboard_service:/src:rw"
    working_dir: "/app"
